export const products = [
  {
    id: 3,
    name: 'Laptop Lenovo Ideapad',
    description: '14" The best resolution',
    image: 'image',
    stock: 5,
    likeCounter: 3,
    price: 1500,
    categoryId: 1,
  },
  {
    id: 2,
    name: 'Laptop HP Pavillion',
    description: 'The best partner for your tasks',
    image: 'image',
    stock: 4,
    likeCounter: 3,
    price: 1800,
    categoryId: 2,
  },
  {
    id: 3,
    name: 'Laptop AMD Ryzen',
    description: 'Only for gamers',
    image: 'image',
    stock: 7,
    likeCounter: 3,
    price: 2000,
    categoryId: 3,
  },
];
