import { ApiProperty } from '@nestjs/swagger';
import { Exclude, Expose } from 'class-transformer';

@Exclude()
export class UserDto {
  @ApiProperty({ description: 'User id - autogenerated' })
  @ApiProperty({ example: 1 })
  @Expose()
  id: number;

  @ApiProperty({ description: 'User name' })
  @ApiProperty({ example: 'Christian' })
  @Expose()
  name: string;

  @ApiProperty({ description: 'User role, true means user is a manager' })
  @ApiProperty({ example: true })
  @Expose()
  isManager: boolean;

  @ApiProperty({ description: 'user lastname' })
  @ApiProperty({ example: 'Sagastegui' })
  @Expose()
  lastname: string;

  @ApiProperty({ description: 'User email' })
  @ApiProperty({ example: 'mail@mail.com' })
  @Expose()
  email: string;
}
